defaults:
  - default
  - _self_

_target_: helpers.models.modules.graph_builder.DistanceGraphBuilder

use_windows: True
window_size: 100
stride: 50

distance_file: data/distances_3d.csv
distance_threshold: 1