model:
  _target_: helpers.models.baseline.SimpleLSTM
  input_dim: 19
  hidden_dim: 64
  num_layers: 1
  dropout: 0.2
username: cizinsky
seed: 42
debug: true
output_dir: /scratch/izar/cizinsky/netml/outputs
logger:
  project: seizure-prediction
  tags:
  - dev
  - baseline
data:
  trn_frac: 0.9
  batch_size: 512
  num_workers: 10
  root: /scratch/izar/cizinsky/netml/data
  prefetch: true
  signal_transform: fft_filtering
optim:
  lr: 0.001
  weight_decay: 0.0
trainer:
  max_epochs: 1000
  accelerator: gpu
  devices: 1
  checkpoint_every_n_epochs: 250
  grad_clip: 0.0
  precision: 32
