defaults:
  - default
  - _self_

_target_: helpers.models.modules.temporal.Modular1DCNN
num_classes: 1
use_batchnorm: true
in_channels: 19
conv_layers:
  - out_channels: 64
    kernel_size: 11
    stride: 1
    padding: 5
    pool: true
  - out_channels: 128
    kernel_size: 11
    stride: 1
    padding: 5
    pool: true
  - out_channels: 256
    kernel_size: 11
    stride: 1
    padding: 5
    pool: false