defaults:
  - default
  - _self_

_target_: helpers.models.modules.temporal.Modular1DCNN
num_classes: 1
use_batchnorm: true
in_channels: 19
conv_layers:
  - out_channels: 64
    kernel_size: 13
    stride: 1
    padding: 6
    pool: true
  - out_channels: 128
    kernel_size: 9
    stride: 1
    padding: 4
    pool: true
  - out_channels: 256
    kernel_size: 5
    stride: 1
    padding: 2
    pool: false