defaults:
  - default
  - _self_

_target_: helpers.models.modules.graph.ModularGraph
conv_layers:
  - _target_: torch_geometric.nn.GCNConv
    in_channels: 354
    out_channels: 128
  - _target_: torch_geometric.nn.GCNConv
    in_channels: 128 # Matching out_channels of previous layer
    out_channels: 128
activation: gelu
use_batchnorm: False
pool_type: mean
num_classes: 1